debug: true

redis:
  hostname: "localhost"
  port: 6379
  password: "yourpasswordhere"

service:
  id: "hub-1"
  group: "hub"
  region: "us"
  branch: "dev"
  address: "127.0.0.1"
  publicAddress: "127.0.0.1"